### ISSUE TITLE
SASS file

### ISSUE THREAD

**Issue by lsmun** [sean-spatrick/WolfieSync#2]
Did you use SASS to compile the CSS? If so could you upload that? If not, let me know and I can get started on that.

**Comment by sean-spatrick** [comment]
I did not get a chance to learn/use SASS to compile the CSS. If you want to get started, that would be fantastic!

**Comment by lsmun** [comment]
No problem! I'll close this issue when I get it up then.

**Comment by lsmun** [comment]
Old issue.
